; Aktivierung/Modus via ENV steuern
xdebug.mode=${XDEBUG_MODE}
xdebug.start_with_request=trigger
xdebug.client_port=9003

; Host je nach Setup:
; - Docker Desktop (Windows/WSL/macOS): host.docker.internal
; - Reines Linux: ggf. gateway.docker.internal oder Host-IP
xdebug.client_host=${XDEBUG_CLIENT_HOST}
xdebug.discover_client_host=1

; optional
;xdebug.log=/tmp/xdebug.log
;xdebug.log_level=0
;xdebug.max_nesting_level=512
