#######################################################################
# STOCK
#######################################################################
name: ${DOCKER_PROJECT_NAME}

services:

  #######################################################################
  # PHP (FPM)
  #######################################################################
  php:
    container_name: ${DOCKER_PROJECT_NAME}-php
    restart: unless-stopped
    #    user: "1000:1000"
    build:
      context: ${DOCKER_DEV_FOLDER}/docker/image/php-fpm
      args:
        - COMPOSER_VERSION=${DOCKER_COMPOSER_VERSION}
        - PHP_VERSION=${DOCKER_PHP_VERSION}
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=remote_host=host.docker.internal
    volumes:
      - "${DOCKER_PROJECT_FOLDER}:/code"
    expose:
      - "9000"
    networks:
      euripnet:


  #######################################################################
  # Nginx
  #######################################################################
  nginx:
    container_name: ${DOCKER_PROJECT_NAME}-nginx
    build: ${DOCKER_DEV_FOLDER}/docker/image/nginx-laravel
    restart: unless-stopped
    #    user: "1000:1000"
    #    build:
    #      context: ../docker/image/nginx
    #      dockerfile: ../docker/image/nginx/Dockerfile
    expose:
      - "80"
    ports:
      - "7777:80"
    volumes:
      - "${DOCKER_PROJECT_FOLDER}:/code"
    depends_on:
      - php
    links:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aaa.rule=Host(`${DOCKER_NGINX_HOST}`)"
    environment:
      - DOCKER_NGINX_HOST=${DOCKER_NGINX_HOST}
    networks:
      euripnet:
        aliases:
          - "${DOCKER_NGINX_HOST}"


#######################################################################
# NETWORKS
#######################################################################
networks:
  euripnet:
    external: true
