#######################################################################
# STOCK
#######################################################################
name: ${DOCKER_PROJECT_NAME}

services:

  #######################################################################
  # PHP (FPM)
  #######################################################################
  php:
    container_name: ${DOCKER_PROJECT_NAME}-php
    restart: unless-stopped
    #    user: "1000:1000"
    build:
      context: ${DOCKER_DEV_FOLDER}/docker/image/php-fpm
      args:
        - COMPOSER_VERSION=${DOCKER_COMPOSER_VERSION}
        - PHP_VERSION=${DOCKER_PHP_VERSION}
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=remote_host=host.docker.internal
    volumes:
      - "${DOCKER_PROJECT_FOLDER}:/code"
    expose:
      - "9000"
    networks:
      euripnet:


  #######################################################################
  # Nginx
  #######################################################################
  nginx:
    container_name: ${DOCKER_PROJECT_NAME}-nginx
    build: ${DOCKER_DEV_FOLDER}/docker/image/nginx-symfony
    restart: unless-stopped
    #    user: "1000:1000"
    #    build:
    #      context: ../docker/image/nginx
    #      dockerfile: ../docker/image/nginx/Dockerfile
    expose:
      - "80"
    volumes:
      - "${DOCKER_PROJECT_FOLDER}:/code"
    depends_on:
      - php
    links:
      - php
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${DOCKER_PROJECT_NAME}.rule=Host(`${DOCKER_NGINX_HOST}`)"
    environment:
      - DOCKER_NGINX_HOST=${DOCKER_NGINX_HOST}
    networks:
      euripnet:
        aliases:
          - "${DOCKER_NGINX_HOST}"


  #######################################################################
  # Node
  #######################################################################
  node:
    image: node:${DOCKER_NODE_VERSION}-alpine
    container_name: ${DOCKER_PROJECT_NAME}-node
    restart: no
    volumes:
      - "${DOCKER_PROJECT_FOLDER}:/code"
    working_dir: "/code"


  #######################################################################
  # yarn-watch
  #######################################################################
#  yarn-watch:
#    #    user: "1000:1000"
#    build:
#      context: ./docker/image/yarn-watch
#      args:
#        - NODE_VERSION=${DOCKER_NODE_VERSION?}
#    restart: no
#    volumes:
#      - "${DOCKER_PROJECT_FOLDER}:/code"
#    working_dir: "/code"


#######################################################################
# NETWORKS
#######################################################################
networks:
  euripnet:
    external: true
